INC_LIBEVENT       =  

all: server client
server:
	g++ -g server.cpp -o server 
client:
	g++ -g client.cpp -o client 
test:
	g++ -g test.cpp -o test
test2:
	g++ -g test2.cpp -o test2
clean:
	rm -rf server client test test2
